name: Run linter and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Test with tox
      run: |
        tox
